### ISSUE TITLE
Does not consider localization

### ISSUE THREAD

**Issue by cartman300** [Sidneys1/KeyStates#1]
In your example project, on my keyboard when i type J K L Č Ć, i get J K L [ ]

**Comment by Sidneys1** [comment]
Correct. This is due to the way windows handles localizable virtual keys. Any key named "OEM_#" are localizable. I hardcoded the most likely layout, but for international solutions the OEM keys will need to be mapped manually. E.g. instead of using e.Key.ToChar(), use a switch first testing for OEM keys.

Sent from my Windows Phone
________________________________

**Comment by cartman300** [comment]
What about implementing this instead?

http://msdn.microsoft.com/en-us/library/windows/desktop/ms646306%28v=vs.85%29.aspx

**Comment by Sidneys1** [comment]
I'll look into it! You would still have to hardcode shift-states, but that is a much better solution than hard coding everything;

Sent from my Windows Phone
________________________________

**Comment by Sidneys1** [comment]
Implemented [ToUnicode](http://msdn.microsoft.com/en-us/library/windows/desktop/ms646320(v=vs.85).aspx) instead. e9b707921ffddfdb5a8873ee0b4b7669c5918183
